export interface TraitCategory {
  id: string;
  label: string;
  traits: string[];
}

export const TRAIT_CATEGORIES: TraitCategory[] = [
  {
    id: 'personality',
    label: 'Personality',
    traits: [
      'Optimistic',
      'Pessimistic',
      'Introverted',
      'Extroverted',
      'Ambitious',
      'Lazy',
      'Brave',
      'Cowardly',
      'Honest',
      'Deceptive',
      'Loyal',
      'Treacherous',
      'Compassionate',
      'Cruel',
      'Curious',
      'Indifferent',
      'Humble',
      'Arrogant',
    ],
  },
  {
    id: 'archetypes',
    label: 'Archetypes',
    traits: [
      'The Hero',
      'The Mentor',
      'The Shadow',
      'The Herald',
      'The Threshold Guardian',
      'The Shapeshifter',
      'The Trickster',
      'The Ally',
      'The Rebel',
      'The Caregiver',
      'The Creator',
      'The Ruler',
      'The Magician',
      'The Sage',
      'The Innocent',
    ],
  },
  {
    id: 'physical',
    label: 'Physical',
    traits: [
      'Tall',
      'Short',
      'Muscular',
      'Thin',
      'Scarred',
      'Beautiful',
      'Plain',
      'Athletic',
      'Clumsy',
      'Agile',
      'Strong',
      'Weak',
      'Sickly',
      'Robust',
    ],
  },
  {
    id: 'social',
    label: 'Social',
    traits: [
      'Charismatic',
      'Awkward',
      'Popular',
      'Outcast',
      'Leader',
      'Follower',
      'Wealthy',
      'Poor',
      'Educated',
      'Uneducated',
      'Famous',
      'Unknown',
    ],
  },
];
